### PR TITLE
Added autocommand to decorator list

### PR DESCRIPTION
**Pull request by Lucretiel**

### CODE REVIEW

**Comment by lord63** [comment]
Thanks for the PR!
By the way, is this package that used to create CLI? Is this package similar to [click](https://github.com/mitsuhiko/click)? Cause we may not accept packages have duplicated ideas in the existed list.
Anyway, I'll leave the PR open for a while and let others review on it :)

**Comment by Lucretiel** [comment]
It is similar to click, yes. It behaves much differently, though– click uses nested decorators to list out inidividual command line arguments, while autocommand much more smartly just infers it from the function signature. Click is more focused on power and completeness, supporting many different arrangements of arguments and subcommands, while autocommand is focused on simplicity and python boilerplate reduction, with features like automatic argument determination, automatic invocation, and asyncio loop boostrapping. 90% of the time, the entire invocation of autocommand is `@autocommand(__name__)`. All the rest is inferred from the function arguments.

**Comment by Lucretiel** [comment]
For instance, click lists this as its first example:

```python
@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)

if __name__ == '__main__':
    hello()
```

In autocommand, this looks like this:

```python
@autocommand.autocommand(__name__)
def main(count: "Number of greetings." =1,
         name: "The person to greet"):
    for x in range(count):
        print("Hello {}!".format(name))
```

**Comment by lord63** [comment]
Put it besides the click library, thanks :cake:

**Pull request closed without merging**
